version: '3.1'

services:
  db:
    build: .
    container_name: nestcraft-db
    restart: always
    ports:
      - "54632:5432"
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=nestcraft
